### PR TITLE
Configuring and testing Eclipse code analyzer 

### PR DESCRIPTION
**Pull request by kd0aij**
@dagar This Eclipse project and codan settings results in 1 error and 837 warnings immediately after "Run C/C++ Code Analysis" at the project level (Eclipse Mars). 
All of the warnings that I've looked at appear to be valid. (mostly "member not initialized")

The single error also appears to be valid:

```
Description Resource    Path    Location    Type
Assignment to itself 'd(internal::random<Index>(0,d.size()-1)) = d(internal::random<Index>(0,d.size()-1))'  svd_fill.h  /PX4Firmware/src/lib/eigen/test line 31 Code Analysis Problem
```

I think symbol resolution is badly broken; I picked a particular unresolved symbol, found the required include file, added it to the path list, and the error did not go away on reindexing and rerunning code analysis.

### CODE REVIEW

**Comment by dagar** [comment]
This is looking really good. Overall only 37 errors for me with eclipse 3.8 and CDT 8.3.

**Comment by LorenzMeier** [comment]
@kd0aij Did you mean to send this PR against your own repo or do you want me to review it for PX4/Firmware?

**Comment by kd0aij** [comment]
@LorenzMeier As I said above, I think symbol resolution is broken in Eclipse/CDT/codan. This branch is for potential exploration of the problem, but unless you intend to use Eclipse/CDT for static code analysis (instead of Travis, Coverity or whatever), it's not generally relevant for PX4.

**Comment by kd0aij** [comment]
@dagar merged upstream master with cmake build, generated Eclipse project file using command
cmake -G"Eclipse CDT4 - Unix Makefiles" (is this the right way to do it?)
.project file is now 4457 lines long, but Eclipse code analysis reports 57,919 errors, including a lot of unresolved and ambiguous symbols. 

oops, I did that on my fork of the master branch, not this branch

**Comment by dagar** [comment]
I'm not really sure. With other (simpler) projects I've had this work pretty well. With cmake eclipse _should_ now have every last piece of information available to the build.

**Comment by kd0aij** [comment]
@dagar @LorenzMeier  I installed Qt Creator 3.5.1 to compare its capabilities for C++ static code analysis to Eclipse... 
Interestingly, it fails to find __EXPORT using a C++ symbol search, while Eclipse finds the #define instantly. With Qt, I had to do a text search which resulted in over 600 hits.

And the free version of Qt has no C++ static analysis tools at all, so there are no "bothersome" errors and warnings to deal with :)

Let me know if I'm missing something, it would be nice to have a faster IDE which actually could find C++ symbol definitions.

**Comment by LorenzMeier** [comment]
Creator will not resolve system API like that from NuttX or the export macros. Let us know if it fails for an actual part of the flight stack, which is what we care about.

**Comment by kd0aij** [comment]
Search for C++ symbol "vehicle_status_s" returns hit for "_vehicle_status_sub" in fw_att_control, but doesn't find the result I needed in mavlink_messages.cpp. Doesn't work in Eclipse either though. It would be nice to understand why neither IDE thinks this is a C++ symbol in mavlink_messages.cpp, and why Qt thinks "int _vehicle_status_sub" is the same symbol as "vehicle_status_s".

qt_findusage

**Comment by LorenzMeier** [comment]
Try the simple case first: CRTL-click a symbol and let us know if that works. This is what people need.

Also try that with function calls and try autocomplete (Ctrl, then space).

Any of these have to work, because those are what you would not get from a Github or desktop search query.

**Comment by kd0aij** [comment]
ctrl-click does nothing, and I can't find any bindings for it
autocomplete looks OK
ctrl+shift+U works only on symbols which highlight when clicked

**Comment by kd0aij** [comment]
@dagar I'm ready to give up on QtCreator. Very flaky on Ubuntu 15.10 and I can find no way to change build targets without editing CMakeLists.txt and creating a new "project" each time.
At least with Eclipse, I can have a project for each target.
Are you still using Eclipse, or have you switched to qtcreator?

**Comment by dagar** [comment]
I'm still using the committed .project/.cproject files. It's a 90% solution for me. I can't trust most of the problems eclipse finds, but it still allows me to open almost all declarations, find call hierarchies, etc. Using cmake to generate the eclipse project works a bit better, but eclipse is much happier if you generate out of tree, which means not using the included Makefile helpers to update submodules, or set the right config for fmuv2, posix, etc. This is currently a pain for me because I'm jumping between branches with submodules constantly changing.

So overall it could be better, but I still like it more than qtcreator. Alternatively CLion might be worth trying. https://www.jetbrains.com/clion/ It uses cmake as its native project format.

@LorenzMeier Why were the eclipse project files renamed template_?

**Comment by kd0aij** [comment]
I used cmake recently (after QtCreator quit working reliably) to create out-of-tree project files for Eclipse/CDT4/Ninja, one for px4fmu-v2_default and another for px4fmu-v4_default. In each project, the all and upload targets seem to do exactly the same thing as make all and make upload, but I wouldn't be surprised if a few submodule changes break them and I have to start over. For now, all I have to do is switch projects to move from PixRacer to FMUv2 configuration. For a while I had two git working trees but it got too confusing. I think I'll try that again with an Eclipse project for each in order to reduce the frequency at which I delete and re-clone.

**Pull request closed without merging**
